default_language_version:
    python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        types: [yaml]
    -   id: check-json
        types: [json]
    -   id: check-toml
        types: [toml]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-docstring-first

-   repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args:
        - --remove-all-unused-imports
        - --recursive
        - --remove-unused-variables
        - --in-place
        exclude: |
            (?x)^(
                .*/__init__\.py|
                .*/migrations/.*
            )$

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3.12
        args: [--line-length=100]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify
        - flake8-variables-names
        args:
        - --max-line-length=100
        - --extend-ignore=E203,W503,E231,B008
        - --max-complexity=14
        - --config=setup.cfg

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-python-jose
        - types-passlib
        - pydantic
        args: [--ignore-missing-imports]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

ci:
    autofix_commit_msg: "style: auto fixes from pre-commit hooks"
    autoupdate_commit_msg: "ci: pre-commit autoupdate"
